version: "2.4"

services:
  # The Browser service, adapted from the balena-io-experimental/browser example.
  browser:
    image: bh.cr/balenalabs/browser-aarch64 # IMPORTANT: Update <arch> (e.g., aarch64, amd64)
    container_name: browser
    restart: always
    privileged: true # Required for UDEV to find peripherals like USB mice
    ports:
      - 5011:5011 # Management API
      - 35173:35173 # Chromium debugging port
    volumes:
      - settings:/data # Persist user settings
      # You might need to mount specific device files here if running on bare metal
      # Example: - /dev/input/event*:/dev/input/event*

  # Scheduler service to manage display power/state
  scheduler:
    build: ./scheduler
    container_name: display_scheduler
    restart: always
    privileged: true
    volumes:
      - settings:/data
    environment:
      - DISPLAY=$DISPLAY
      - TZ=America/Los_Angeles
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.1'
    #       memory: 64M


volumes:
  settings:
